---
driver:
  name: vagrant
  network:
    - ["private_network", { ip: "192.168.55.55" }]

provisioner:
  name: chef_zero

platforms:
  - name: debian-9

suites:
  - name: default
    run_list:
      - recipe[desktop::default]
      - recipe[desktop::network_manager]
      - recipe[desktop::vim]
      - recipe[desktop::firefox]
      - recipe[desktop::vagrant]
      - recipe[desktop::nodejs]
