name 'desktop'
maintainer 'Ronald Macmaster'
maintainer_email 'ronnymacmaster@gmail.com'
license 'Apache 2.0'
description 'Personal Desktop Recipes'
long_description 'Chef Recipes for my personal Debian desktops.'
version '0.1.0'
chef_version '>= 13.0'

issues_url 'https://github.com/ronny-macmaster/chef-desktop/issues'
source_url 'https://github.com/ronny-macmaster/chef-desktop'
